#!/usr/bin/python3
"""Sends a POST request to the passed URL with the email as a parameter,
    and finally displays the body of the response."""

import requests
import sys

if __name__ == "__main__":
    url = "http://0.0.0.0:5000/earch_user"
    q = sys.argv[1] 

    payload = {'q': q}
    response = requests.post(url, data=payload)
    try :
        if not response.json():
            #print(response.json())
            print("No result")
        else:
            print(response.json())
    except ValueError:
        print(e)
        print("Not a valid JSON")
